### ISSUE TITLE
Bug: { exit = true } doesn't work correctly for pink Hydras

### ISSUE THREAD

**Issue by ziontee113** [anuvyklack/hydra.nvim#16]
I have this Pink Hydra example:
```lua
Hydra({
	name = "Change Window",
	mode = { "n" },
	body = "<C-w>",
	config = {
		color = "pink",
	},
	heads = {
		{ "<C-h>", "<C-w>h" },
		{ "<C-j>", "<C-w>j" },
		{ "<C-k>", "<C-w>k" },
		{ "<C-l>", "<C-w>l" },

		{
			"p",
			function()
				print("hello man")
			end,
			{ exit = true },
		},

		{ "q", nil, { exit = true, nowait = true } },
	},
})

```
Expected behavior when pressing `<C-w>p`: `hello man` gets printed.
Actual behavior: nothing happens.

If Hydra gets entered with other heads, `p` works correctly.
If Hydra head is `p`, it does nothing or some other weird behaviors.

**Comment by anuvyklack** [comment]
From the [README](https://github.com/anuvyklack/hydra.nvim#exit-1):
> Note: All exit heads are also private.

Because I don't see much sense in public exit heads: what hydra should do in this case? Activate and immediately exit?
Just bind `vim.keymap.set('n', 'p', function() print(...) end)` and don't torture the hydra.

**Comment by ziontee113** [comment]
Err.. You can activate the hydra with a different head. Of course it doesn't makes sense to activate then exit. It becomes useful when you already activated the Hydra with other heads, and you want to execute some commands then immediately exit that Hydra.
