### ISSUE TITLE
[Feature Request] New hydra that can be entered without waiting for a head. 

### ISSUE THREAD

**Issue by AdrienDML** [anuvyklack/hydra.nvim#20]
Here is the feature:
I have an hydra but i want to enter it without having to press any head. 

Motivation:
Sometimes I want to enter an hydra but mess up the first key of a head, then the hydra is not entered and neovim interprets my following key presses messing everything up. 

If this is possible and fits in the plugin view how should it be implemented ?
I thought that adding a boolean field in the config table would be a reasonable option.

**Comment by tmgast** [comment]
You should already be able to do that with `invoke_on_body` in the config:
``` lua
config = {
  invoke_on_body = true
}
```

**Comment by AdrienDML** [comment]
Thanks and sorry missed that option :smile:.
