### ISSUE TITLE
Can't use <Plug> for mapping

### ISSUE THREAD

**Issue by ruanyouxing** [anuvyklack/hydra.nvim#21]
How to use ```<Plug>``` to trigger a command?
Example :
```
local hint = [[_p_: Pick buffer]]
local hydra = require'hydra'
     hydra.setup{
     hint = hint,
     heads = {
           {'p','<Plug>(cokeline-pick-select)'},
     }.
}
```
But it seems didn't work
```E492: Not an editor command: (cokeline-pick-select)```

**Comment by singlexyz** [comment]
This works:

1. Add option: `{ expr = true }`
2. Use string in rhs, `"'<Plug>...'"`

```vim
Hydra({
  name = "Move line",
  mode = "n",
  body = "gm",
  heads = {
    { "j", "'<Plug>MoveLineDown'", { expr = true } },
    { "k", "'<Plug>MoveLineUp'", { expr = true } },
  },
})
```

**Comment by anuvyklack** [comment]
You shouldn't need it. I don't use cokeline. Can you provide minimal config?

Because I personaly use `<Plug>...` mappings in [this hydra](https://github.com/anuvyklack/hydra.nvim/wiki/Quick-words) and they just work.

**Comment by ruanyouxing** [comment]
@anuvyklack here 
![hydra](https://user-images.githubusercontent.com/87190231/179443647-089b73c2-f153-4282-a74a-469c08d867b0.png)
And this is the error
![error](https://user-images.githubusercontent.com/87190231/179443771-9df7bb44-89d7-4dae-b295-532da8743170.png)

**Comment by ruanyouxing** [comment]
@singlexyz Thanks, it worked in that way

**Comment by anuvyklack** [comment]
It is not a good minimal config, because I can't paste a screenshot into Neovim and check myself.

**Comment by anuvyklack** [comment]
`<Plug>...` is a name of a keybinding, not a vimscript expression. That's why you get this error. Delete the `expr = true` option. And try again.

**Comment by ruanyouxing** [comment]
@anuvyklack  Thanks, that helped me
