### ISSUE TITLE
Hydra hangs after pressing any key before `timeoutlen` elapsed

### ISSUE THREAD

**Issue by Gaulm** [anuvyklack/hydra.nvim#24]
If I type any key after `teal` hydra `body` and before `timeoutlen` elapsed, the hint overlay remains open and the hydra is not executed.

I have this problem with `teal` and `blue` hydras, but probably it's valid for any color.

**Comment by anuvyklack** [comment]
Can't reproduce. I use `teal` hydra for Telescope and my `timeoutlen` is 1000.
