### ISSUE TITLE
[Bug] Hint window disapear while changing tab.

### ISSUE THREAD

**Issue by AdrienDML** [anuvyklack/hydra.nvim#26]
I have extended the comunity hydra to support tabs. But the hint window disapears. It is a minor inconvinience but can be a bit frustrating not knowing if i'm still in the hydra. Here is a gif demonstrating the bug:
![hydradisapear](https://user-images.githubusercontent.com/31519713/179872822-dbf1e659-a340-4de3-8b30-d1c3d71cbda5.gif)

**Comment by anuvyklack** [comment]
fix 034a0bbbb0e1215b98ee114cfc0f367241ae49ef

**Comment by AdrienDML** [comment]
Thx that was a quick fix ^^
