### ISSUE TITLE
Hint bar stays at old position after Neovim resizes

### ISSUE THREAD

**Issue by Frederick888** [anuvyklack/hydra.nvim#27]
### Steps to reproduce

Hydra version: b763432e6f0b8f45313fda5733c25f33b939c82a

1. Trigger Hydra
2. Make Neovim taller (I'm using tmux so I just made the tmux pane taller)
3. Trigger Hydra again

### Expected outcome

Hydra hint bar is right above status bar

### Actual outcome

Hydra hint bar stays at its old position, which is in the middle of my current buffer (I temporarily bumped up timeout to capture the screenshot)

<img width="878" alt="image" src="https://user-images.githubusercontent.com/4507647/179882512-9ad9de11-9989-4946-9a52-93b38c373edf.png">

Configuration:
```lua
local Hydra = require('hydra')
local splits = require('smart-splits')

Hydra({
  name = "Split movements and resizing",
  mode = 'n',
  body = '<C-w>',
  config = {
    timeout = 250,
  },
  heads = {
    { 'h', [[<cmd>try | wincmd h | catch /^Vim\%((\a\+)\)\=:E11:/ | close | endtry<CR>]] },
    { 'j', [[<cmd>try | wincmd j | catch /^Vim\%((\a\+)\)\=:E11:/ | close | endtry<CR>]] },
    { 'k', [[<cmd>try | wincmd k | catch /^Vim\%((\a\+)\)\=:E11:/ | close | endtry<CR>]] },
    { 'l', [[<cmd>try | wincmd l | catch /^Vim\%((\a\+)\)\=:E11:/ | close | endtry<CR>]] },
    { 'H', splits.resize_left },
    { 'J', splits.resize_down },
    { 'K', splits.resize_up },
    { 'L', splits.resize_right },
  },
})
```

**Comment by anuvyklack** [comment]
fix in b882135a72243211a93106bd8e3edd835d767e6a

**Comment by Frederick888** [comment]
@anuvyklack Thanks for the fix!

However I'm afraid there's another way to reproduce this issue on 034a0bbbb0e1215b98ee114cfc0f367241ae49ef. Instead of resizing Neovim, if you reduce `cmdheight` after triggering Hydra for the first time, it'll again stay at its old position a few lines above status line.

**Comment by anuvyklack** [comment]
I will fix it, but... How often do you change the `cmdheight`?

**Comment by Frederick888** [comment]
I seldom change it myself but I use nvim-dap-ui and there happens to be https://github.com/rcarriga/nvim-dap-ui/issues/108 😅

Anyway I agree this isn't crucial.

**Comment by anuvyklack** [comment]
Done da0c2e515133c4b8a9ba3ad5308db596610329bd
