### ISSUE TITLE
Example of execution on entry 

### ISSUE THREAD

**Issue by mvphilip** [anuvyklack/hydra.nvim#28]
Hello, This is a great plugin. I have a hack for invoke_on_body that may work better for navigation type Hydras. I have a lot of buffers that I often toggle between. I previously used vim-submode to enable this. In vim-submode, the entry into any submode will first trigger the action and wait for further keystrokes. In hydra you enter a mode and then you have to type another key to get an action. If you only want to move to the left buffer for example this would require 1 more keystroke than vim-submode.

This hack for navigating between buffers would eliminate the need for the extra keystroke:

```
local buf_config = {
 config = {
  invoke_on_body = true,
  on_enter = function()
    -- Each hydra must be named by it's hydra head action name
    vim.api.nvim_input(statusline.get_name())
  end,
}}

-- Buffer navigation maps
local buf_head = {
  { "h", "<C-w>h", { desc = "←" } },
  { "l", "<C-w>l", { desc = "→" } },
  { "j", "<C-w>j", { desc = "↑" } },
  { "k", "<C-w>k", { desc = "↓" } },

}

for _,key in ipairs({'l', 'k', 'j', 'h'} ) do
  Hydra(
  {
    name = key,
    mode = { 'n', 't'},
    config = buf_config,
    body = "<leader>" .. key,
    heads = buf_head,
  })
end
```

With the above, <leader>h would immediately move to the left buffer and wait for further inputs. 

Thanks,

-mp

**Comment by anuvyklack** [comment]
As I get, you create four hydras which are differing only in body keys:
- `<leader>h`
- `<leader>j`
- `<leader>k`
- `<leader>l`

But if you set `invoke_on_body = false` and `body = <leader>` with the same heads, wouldn't you get the same result?
