### ISSUE TITLE
Feature - Enable hydra only for particular buff type

### ISSUE THREAD

**Issue by JoseConseco** [anuvyklack/hydra.nvim#32]
The issue I have now:  **DAP** spawns multiple windows (watches, repl, etc), next to my code, thus when enabling DAP_hydra - I use `buffer` option to only attach hydra hotkeys to my active buffer (source code). This way I can edit  other dap spawned windows no problem (without conflicts with hydra).
Problem is - if dap steps into another python file, hydra wont work in that file. 
So I wish we could attach hotkeys based on file type  eg. something like :   
  hydra_ftype =  active_buff.file_type
This way hydra would not affect **Dap  repl,** **dap watches**, but it will work when stepping source code around files.

**Comment by zdcthomas** [comment]
Why not define the Hydra in an autocmd for a given filetype and use the [buffer](https://github.com/anuvyklack/hydra.nvim/blob/c70facc87141f64162aca519acfd18aa85e06329/doc/hydra.txt#L341) option?

**Comment by JoseConseco** [comment]
i just tried and it did not work:

```
		vim.api.nvim_create_autocmd({"BufEnter"}, { --FocusGained
			pattern = "*.py",
			callback = function()
				print('Dap activate')
				dap_hydra:activate()
			end,
			group = dap_group,
		})
```
It still only will use Hydra hotkeys in first buffer. When debugger goes into anothe file, I can see 'Dap Active' but hydra hotkeys wont work ....

**Comment by zdcthomas** [comment]
I meant actually define it in that autocommand with the `buffer` option. Take a look at `:h hydra-config.buffer`

**Comment by JoseConseco** [comment]
It does not seem to matter if   the buffer option is there or not -  with autocmd this doesn not work.  I'm not sure if you got it working on you end, or you just post what you think could work, but if u got solution that actually works it would be great if you could share the code.

**Comment by zdcthomas** [comment]
I have tried it, and it seems to work for me. Maybe the misunderstanding is that I don't mean `activate` the hydra only for certain file types. Activate (based on [here](https://github.com/anuvyklack/hydra.nvim/blob/aefadd3f61234d5ac51f59057965d44f63126778/doc/hydra.txt#L219) and [here](https://github.com/anuvyklack/hydra.nvim/blob/aefadd3f61234d5ac51f59057965d44f63126778/doc/hydra.txt#L611) in the docs, starts up a hydra; it doesn't define it. 

What I originally meant is something like this:
```lua
vim.api.nvim_create_autocmd({ "FileType" }, {
	group = InitGroupId,
	pattern = { "markdown" },
	callback = function(args)
		local Hydra = require("hydra")

		Hydra({
			name = "Test",
			mode = "n",
			body = "b",
			config = {
				buffer = true,
				-- buffer = args.buf,
			},
			desc = "TRACING FROM SF",
			heads = {
				{
					"h",
					function()
						Pr("Hello!")
					end,
				},
			},
		})
	end,
})
```
In which the Hydra is actually _defined_ inside of the autocmd.

**Comment by JoseConseco** [comment]
I finally found way to auto spawn and close hydra - see https://github.com/anuvyklack/hydra.nvim/issues/77  . Ugly hack with sleep() was required.
