### ISSUE TITLE
silent options doesn't work anymore

### ISSUE THREAD

**Issue by darkangel-ua** [anuvyklack/hydra.nvim#33]
After update I've discovered that `silent` doesn't work in heads and I see command appearing in the command like and from time to time `lualine` disappears from screen. 
```
        heads = {
            { 'h' , ':BufferLineCyclePrev<cr>', { silent = true, desc = 'Prev buffer'} },
            { 'l' , ':BufferLineCycleNext<cr>', { silent = true, desc = 'Next buffer' } },
            { 'q', nil, { exit = true, nowait = true } },
        }
```

**Comment by anuvyklack** [comment]
I don't have much time to fix this issue now, because it is rather tricky. As a temporary solution, you can use `<cmd>` instead of `:` like this:
```lua
{ 'h' , '<cmd>BufferLineCyclePrev<cr>', { desc = 'Prev buffer'} },
```
See `:help <Cmd>`

**Comment by darkangel-ua** [comment]
Interesting :) That works for me. Thanks!
