### ISSUE TITLE
Disabling indent-blankline.nvim in hydra windows

### ISSUE THREAD

**Issue by shaun-mathew** [anuvyklack/hydra.nvim#35]
I am currently using a plugin called [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim/issues) that draws guides for indentation with the exception of some filetypes and buffers that you can manually specify within its config. I'm trying to add hydra buffers to this list, but I can't seem to find out what the buffer name is for hydra floating windows, so that I can disable it.
![2022-08-07_23-16](https://user-images.githubusercontent.com/16690478/183331441-8be9f841-98e7-472f-8764-931003823ed6.png)

**Comment by anuvyklack** [comment]
Hydra set for hint buffers `hydra_hint` filetype. See `:help 'filetype'`

**Comment by shaun-mathew** [comment]
That worked! Thanks!
