### ISSUE TITLE
Does not handle new cmdheight=0 in NeoVim HEAD / 0.8+

### ISSUE THREAD

**Issue by andrewferrier** [anuvyklack/hydra.nvim#4]
NeoVim HEAD / 0.8+ contains a new feature where `cmdheight` can be set to `0` to remove the command line. This seems to confuse hydra; the pop up at the bottom with the hints is offset by an additional line and shows a duplicate of one of the buffers, in a window that occupies only one line.

Not sure how urgent you consider a fix here to be - to be fair this feature in NeoVim is very new and bugfixes are still coming to NeoVim itself. But wanted to put it on your radar.

Thanks for your hard work on this great plugin!

**Comment by anuvyklack** [comment]
Done in 632dc7f999716e180a5efba574f677bfe4931b47
