### ISSUE TITLE
What font support glyphs in the example?

### ISSUE THREAD

**Issue by bangedorrunt** [anuvyklack/hydra.nvim#42]
@anuvyklack Wondering what font you're using. I'm using SFMono patched nerd fonts however there is missing glyphs that can't be rendered by terminal
![image](https://user-images.githubusercontent.com/1514823/189511044-e9556880-5db6-43c2-a146-00dcf9df47fa.png)
<img width="1122" alt="Screen Shot 2022-09-11 at 1 25 36 pm" src="https://user-images.githubusercontent.com/1514823/189511058-8f444934-ed87-4d75-94f4-ce92c237d274.png">

**Comment by anuvyklack** [comment]
Thees are symbols from [Unicode Symbols for Legacy Computing](https://en.wikipedia.org/wiki/Symbols_for_Legacy_Computing). They are available from Unicode 13. I use Kitty terminal (It allows using different fonts for different code points) with DejaVu Sans Mono for Unicode characters. and Inconsolata for ASCII code points.
