### ISSUE TITLE
Display notice while stay in hydra mode

### ISSUE THREAD

**Issue by LintaoAmons** [anuvyklack/hydra.nvim#53]
I want print notice when trigger this command 
But it won't appear until I exit hydra.
Is it possible to display the notify while stay in hydra mod

![image](https://user-images.githubusercontent.com/95092244/192945427-7e9824e1-eedd-4cb0-b627-e0ba5e643eff.png)

![demo](https://user-images.githubusercontent.com/95092244/192945965-1a983882-ca73-4a7f-ae4a-b6cef3f5d6b1.gif)

**Comment by LintaoAmons** [comment]
> Tho notify is async, so it will be executed only when hydra will exit. You can use `vim.wait` function, or make `t`` blue head.

Can you show me a sample code? I'm kind of noob...

**Comment by anuvyklack** [comment]
What sample do you want?

**Comment by LintaoAmons** [comment]
To achieve the goal that display sort of hint message while hit shortcut `t`~ 

I don't know how to use `vim.wait` and still don't know `blue head`...

**Comment by miversen33** [comment]
@LintaoAmons 
This is _not_ tested, but consider instead of using `vim.wait`, [`vim.schedule`](https://neovim.io/doc/user/lua.html)
```vim
vim.schedule({callback})                                      *vim.schedule()*
    Schedules {callback} to be invoked soon by the main event-loop. Useful
    to avoid |textlock| or other temporary restrictions.
```

In practice, this looks like
```lua
{
    "t",
    function()
        cmd "<cmd>WindowsToggleAutowidth<cr>"
        vim.schedule(function() vim.notify "Autowidth toggle triggered")
    end),
    { desc = "Toggle Autowidth" },
},
```

Note again, not tested, but something like this _should_ get you what you are looking for as you are effectively dropping a function into the neovim event loop for future callback. Thus the callback will happen *outside* the context of Hydra and any sort of sync block should be resolved.

**Comment by anuvyklack** [comment]
But this is what happen now: event loop is only one and hydra occupies it.  When you invoke `vim.notify` it is scheduled automatically and executed when event loop is free.

**Comment by LintaoAmons** [comment]
Is there a way that I can print out some hints while still in hydra? Maybe not use `vim.notify`?

**Comment by anuvyklack** [comment]
Read `:help vim.wait`.
```lua
{
   't',
   function()
      vim.cmd('<Cmd>WindowsToggleAutowidth<CR>')
      vim.wait(1, function()
         vim.notify('Autowidth toggle triggered')
      end)
   end,
   { desc = 'Toggle Autowidth'}
}
```

**Comment by anuvyklack** [comment]
Another way, is to make `t` head exit:
```lua
{ 't', <Cmd>WindowsToggleAutowidth<CR>', { exit = true } },
```
